from juego.core.juego import JuegoBase


LENGUAJE_ACTUAL = 'MySQL'
NIVEL_ACTUAL = 6
FONDO_ACTUAL = 'mysql'


class NivelMySQL06(JuegoBase):
    # Cada archivo conserva su propia configuración.
    LENGUAJE_ACTUAL = LENGUAJE_ACTUAL
    NIVEL_ACTUAL = NIVEL_ACTUAL
    FONDO_ACTUAL = FONDO_ACTUAL
    JUGADOR_X_INICIAL = 170

    # Usa valores pequeños.
    # Negativo = sube.
    # Positivo = baja.
    AJUSTE_Y_JUGADOR =0
    LONGITUD_NIVEL = 9500
    NPC_X = 895
    AJUSTE_Y_NPC = -8
    AJUSTE_Y_SPRITE_MONTANAS = 0
    AJUSTE_Y_SPRITE_SUELO = 0
    AJUSTE_Y_SPRITE_PLANTAS = 0
    CARTEL_FINAL = {
    "x": 8350,
    "ajuste_y": -10,
    "tamano":0.40,
    "mostrar_bloqueado": True,
}
    PISOS = (
        (0, LONGITUD_NIVEL),
    )
    OBSTACULOS = (
    # ==========================================================
    # SECCIÓN 1: ENTRADA MIXTA
    # Calentamiento terrestre y subida corta.
    # ==========================================================
    {
        "tipo": "tronco",
        "imagen": "mysql/tronco.png",
        "x": 620,
        "ajuste_y": -5,
        "ancho": 120,
        "alto": 50,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 15,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 20,
    },
    {
        "tipo": "puas",
        "imagen": "mysql/pinchos.png",
        "x": 820,
        "cantidad": 2,
        "separacion": 10,
        "ajuste_y": -5,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 25,
        "hitbox_offset_y": 30,
        "hitbox_reducir_ancho": 45,
        "hitbox_reducir_alto": 25,
    },
    {
        "tipo": "bloque",
        "imagen": "mysql/bloque.png",
        "x": 1080,
        "ajuste_y": -5,
        "ancho": 100,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "cofre",
        "imagen": "mysql/cofre.png",
        "x": 1090,
        "ajuste_y": -41,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 1280,
        "ajuste_y": -65,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 1500,
        "ajuste_y": -125,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 1720,
        "ajuste_y": -65,
        "ancho": 160,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },

    # ==========================================================
    # SECCIÓN 2: PUENTE SQL SUSPENDIDO
    # Río de pinchos con subida, bajada y plataformas variadas.
    # ==========================================================
    {
        "tipo": "puas",
        "imagen": "mysql/pinchos.png",
        "x": 2050,
        "cantidad": 12,
        "separacion": 10,
        "ajuste_y": -5,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 25,
        "hitbox_offset_y": 30,
        "hitbox_reducir_ancho": 45,
        "hitbox_reducir_alto": 25,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 2010,
        "ajuste_y": -60,
        "ancho": 160,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 2240,
        "ajuste_y": -125,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 2470,
        "ajuste_y": -185,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "tronco",
        "imagen": "mysql/tronco.png",
        "x": 2700,
        "ajuste_y": -125,
        "ancho": 150,
        "alto": 40,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 12,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 15,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 2930,
        "ajuste_y": -185,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "cofre",
        "imagen": "mysql/cofre.png",
        "x": 2980,
        "ajuste_y": -220,
        "ancho": 40,
        "alto": 25,
        "hitbox_offset_x": 8,
        "hitbox_offset_y": 6,
        "hitbox_reducir_ancho": 16,
        "hitbox_reducir_alto": 8,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 3160,
        "ajuste_y": -120,
        "ancho": 160,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 3390,
        "ajuste_y": -60,
        "ancho": 160,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },

    # ==========================================================
    # SECCIÓN 3: CORREDOR DE COLUMNAS
    # Obstáculos terrestres con una torre central.
    # ==========================================================
    {
        "tipo": "cofre",
        "imagen": "mysql/cofre.png",
        "x": 3830,
        "ajuste_y": 0,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "puas",
        "imagen": "mysql/pinchos.png",
        "x": 3950,
        "cantidad": 2,
        "separacion": 10,
        "ajuste_y": -5,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 25,
        "hitbox_offset_y": 30,
        "hitbox_reducir_ancho": 45,
        "hitbox_reducir_alto": 25,
    },
    {
        "tipo": "bloque",
        "imagen": "mysql/bloque.png",
        "x": 4180,
        "ajuste_y": -5,
        "ancho": 100,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "bloque",
        "imagen": "mysql/bloque.png",
        "x": 4180,
        "ajuste_y": -41,
        "ancho": 100,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "cofre",
        "imagen": "mysql/cofre.png",
        "x": 4190,
        "ajuste_y": -77,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "puas",
        "imagen": "mysql/pinchos.png",
        "x": 4410,
        "cantidad": 2,
        "separacion": 10,
        "ajuste_y": -5,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 25,
        "hitbox_offset_y": 30,
        "hitbox_reducir_ancho": 45,
        "hitbox_reducir_alto": 25,
    },
    {
        "tipo": "tronco",
        "imagen": "mysql/tronco.png",
        "x": 4620,
        "ajuste_y": -5,
        "ancho": 120,
        "alto": 50,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 15,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 20,
    },
    # ==========================================================
    # SECCIÓN 4: CORONA AÉREA
    # Incluye un salto hacia atrás y un descenso prolongado.
    # ==========================================================
    {
        "tipo": "puas",
        "imagen": "mysql/pinchos.png",
        "x": 5000,
        "cantidad": 11,
        "separacion": 10,
        "ajuste_y": -5,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 25,
        "hitbox_offset_y": 30,
        "hitbox_reducir_ancho": 45,
        "hitbox_reducir_alto": 25,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 4960,
        "ajuste_y": -65,
        "ancho": 160,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 5190,
        "ajuste_y": -130,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 5420,
        "ajuste_y": -195,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 5650,
        "ajuste_y": -260,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 5500,
        "ajuste_y": -330,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "cofre",
        "imagen": "mysql/cofre.png",
        "x": 5550,
        "ajuste_y": -365,
        "ancho": 40,
        "alto": 25,
        "hitbox_offset_x": 8,
        "hitbox_offset_y": 6,
        "hitbox_reducir_ancho": 16,
        "hitbox_reducir_alto": 8,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 5740,
        "ajuste_y": -330,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "tronco",
        "imagen": "mysql/tronco.png",
        "x": 5980,
        "ajuste_y": -260,
        "ancho": 150,
        "alto": 40,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 12,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 15,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 6220,
        "ajuste_y": -190,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 6460,
        "ajuste_y": -120,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 6680,
        "ajuste_y": -60,
        "ancho": 160,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },

    # ==========================================================
    # SECCIÓN 5: DOBLE RUTA FINAL
    # Puede avanzarse por tierra o por las plataformas superiores.
    # ==========================================================
    {
        "tipo": "tronco",
        "imagen": "mysql/tronco.png",
        "x": 6970,
        "ajuste_y": -5,
        "ancho": 120,
        "alto": 50,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 15,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 20,
    },
    {
        "tipo": "puas",
        "imagen": "mysql/pinchos.png",
        "x": 7140,
        "cantidad": 2,
        "separacion": 10,
        "ajuste_y": -5,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 25,
        "hitbox_offset_y": 30,
        "hitbox_reducir_ancho": 45,
        "hitbox_reducir_alto": 25,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 7080,
        "ajuste_y": -70,
        "ancho": 160,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "bloque",
        "imagen": "mysql/bloque.png",
        "x": 7310,
        "ajuste_y": -135,
        "ancho": 140,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "bloque",
        "imagen": "mysql/bloque.png",
        "x": 7480,
        "ajuste_y": -5,
        "ancho": 100,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "cofre",
        "imagen": "mysql/cofre.png",
        "x": 7490,
        "ajuste_y": -41,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "puas",
        "imagen": "mysql/pinchos.png",
        "x": 7610,
        "cantidad": 3,
        "separacion": 10,
        "ajuste_y": -5,
        "ancho": 80,
        "alto": 50,
        "hitbox_offset_x": 25,
        "hitbox_offset_y": 30,
        "hitbox_reducir_ancho": 45,
        "hitbox_reducir_alto": 25,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 7550,
        "ajuste_y": -70,
        "ancho": 160,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 7790,
        "ajuste_y": -135,
        "ancho": 150,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
    {
        "tipo": "fragmento",
        "imagen": "mysql/plataforma.png",
        "x": 8020,
        "ajuste_y": -70,
        "ancho": 160,
        "alto": 36,
        "hitbox_offset_x": 10,
        "hitbox_offset_y": 10,
        "hitbox_reducir_ancho": 20,
        "hitbox_reducir_alto": 10,
    },
)

    PRACTICAS = (
      
    )


CLASE_NIVEL = NivelMySQL06


def ejecutar_nivel(id_jugador: int = 1):
    juego = CLASE_NIVEL(id_jugador=id_jugador)
    juego.ejecutar()


if __name__ == "__main__":
    ejecutar_nivel()
